name: Rust Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build Linux binary
        run: cargo build --release
      - name: Upload Linux binary
        uses: softprops/action-gh-release@v2
        with:
          files: target/release/hotline

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build Windows binary
        run: cargo build --release --target x86_64-pc-windows-gnu
      - name: Upload Windows binary
        uses: softprops/action-gh-release@v2
        with:
          files: target/x86_64-pc-windows-gnu/release/hotline.exe

