name: Manual Rust Build

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  manual-windows-build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build Windows .exe
        run: cargo build --release

      - name: Upload .exe artifact
        uses: actions/upload-artifact@v4
        with:
          name: rust-windows-binary
          path: target/release/*.exe
